[Log_results]
# if not 0, must contain the filepath to the morphoframe which will then be saved into morphoframe_name
# otherwise, `morphoframe_name` is the morphoframe that will be cleaned up
"morphoframe_name" = "ipl_opl"
"morphoframe_filepath" = 0

    # List of checks
    [[Log_results.checks]]
    name = "ipl_p5_vs_p22_in_het"
    filter = "(df['Region']=='IPL') & (df['Condition']=='Development') & (df['Model']=='Cx3cr1_het') & (df['Time'].isin(['P5', 'P22']))"
    crit = "Time"

    [[Log_results.checks]]
    name = "opl_p7_vs_p22_in_het"
    filter = "(df['Region']=='OPL') & (df['Condition']=='Development') & (df['Model']=='Cx3cr1_het') & (df['Time'].isin(['P7', 'P22']))"
    crit = "Time"

    [[Log_results.checks]]
    name = "ipl_p10_vs_p65_in_rd10"
    filter = "(df['Region']=='IPL') & (df['Condition']=='Degeneration') & (df['Model']=='rd10') & (df['Time'].isin(['P10', 'P65']))"
    crit = "Time"

    [[Log_results.checks]]
    name = "opl_p10_vs_p65_in_rd10"
    filter = "(df['Region']=='OPL') & (df['Condition']=='Degeneration') & (df['Model']=='rd10') & (df['Time'].isin(['P10', 'P65']))"
    crit = "Time"



# I would advise saving the cleaned data; value is either `true` or `false` (warning: take note that all the letters are in lower case)
"save_data" = false

# location where to save the data
"save_folderpath" = "results/cell"

# if 0, morphOMICs will automatically create a file prefix, i.e., Morphomics.PID[xxx].[barcode_filter].Cleaned.
# Otherwise, this will be used as the file prefix
"save_filename" = "logged_results"